import streamlit as st
import numpy as np
import plotly.graph_objects as go

from src.data_loader import (
    load_forecasts,
    load_product_history,
)

st.title("Demand Forecast")
st.caption(
    "View predicted product demand over the forecast horizon."
)

forecast_data = load_forecasts()

# ====================================
# No ML output yet
# ====================================

if forecast_data.empty:
    st.info(
        "Forecast results are not available yet. "
        "This page will display predictions once "
        "`data/processed/forecasts.parquet` is generated."
    )

    st.stop()

# ====================================
# Filters
# ====================================

st.sidebar.header("Forecast Filters")

store = st.sidebar.selectbox(
    "Store",
    sorted(forecast_data["store_id"].unique()),
    key="forecast_store",
)

store_forecasts = forecast_data[
    forecast_data["store_id"] == store
]

product = st.sidebar.selectbox(
    "Product",
    sorted(store_forecasts["item_id"].unique()),
    key="forecast_product",
)

product_forecast = (
    store_forecasts[
        store_forecasts["item_id"] == product
    ]
    .sort_values("date")
)

# ====================================
# Historical Demand
# ====================================

history = load_product_history(
    store_id=store,
    item_id=product,
).sort_values("date")

validation_start = product_forecast["date"].min()
validation_end = product_forecast["date"].max()

actuals = history[
    history["date"].between(
        validation_start,
        validation_end
    )
][["date", "sales"]].copy()

comparison = product_forecast.merge(
    actuals,
    on="date",
    how="left",
    validate="one_to_one",
)

comparison = comparison.rename(
    columns={"sales": "actual_sales"}
)

# ====================================
# Metrics
# ====================================

mae = (
    comparison["actual_sales"] - comparison["predicted_sales"]
).abs().mean()

rmse = np.sqrt(
    np.mean(
        (
            comparison["actual_sales"] - comparison["predicted_sales"]
        ) ** 2
    )
)

actual_total = comparison["actual_sales"].sum()
predicted_total = comparison["predicted_sales"].sum()

col1, col2, col3, col4 = st.columns(4)

col1.metric(
    "Actual Demand",
    f"{actual_total:,.0f}",
)

col2.metric(
    "Predicted Demand",
    f"{predicted_total:,.0f}",
)

col3.metric(
    "MAE",
    f"{mae:.2f}",
)

col4.metric(
    "RMSE",
    f"{rmse:.2f}",
)

# =========================================================
# Forecast chart
# =========================================================

st.subheader("Actual vs Predicted Demand")

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=comparison["date"],
        y=comparison["actual_sales"],
        mode="lines",
        name="Actual",
        line=dict(
            color="#7CC4EA",
            width=2,
        ),
    )
)

fig.add_trace(
    go.Scatter(
        x=comparison["date"],
        y=comparison["predicted_sales"],
        mode="lines",
        name="Predicted",
        line=dict(
            color="#fdbb2e",
            width=2.5,
        ),
    )
)

fig.update_layout(
    xaxis_title="Date",
    yaxis_title="Units Sold",
    hovermode="x unified",
)

st.plotly_chart(
    fig,
    use_container_width=True,
)


# =========================================================
# Inventory risk generated by ML workflow
# =========================================================

st.subheader("Demand Pressure")

risk_counts = (
    product_forecast["risk_level"]
    .value_counts()
)

high_days = risk_counts.get("High", 0)
medium_days = risk_counts.get("Medium", 0)
low_days = risk_counts.get("Low", 0)

col1, col2, col3 = st.columns(3)

col1.metric(
    "High-Risk Days",
    high_days,
)

col2.metric(
    "Medium-Risk Days",
    medium_days,
)

col3.metric(
    "Low-Risk Days",
    low_days,
)


# =========================================================
# Table
# =========================================================

with st.expander("View Daily Forecast"):
    st.dataframe(
        comparison[
            [
                "date",
                "actual_sales",
                "predicted_sales",
                "risk_level",
                "inventory_status",
            ]
        ],
        use_container_width=True,
        hide_index=True,
    )